### PR TITLE
Update readme with information about ObjectMapper factory usage

### PR DESCRIPTION
**Pull request by reinterpretcat**

### CODE REVIEW

**Comment by cdimascio** [comment]
Thanks again. Much appreciated!

**Comment by cdimascio** [comment]
i will roll a new version with your changes shortly

**Comment by reinterpretcat** [comment]
Thanks a lot!

**Comment by cdimascio** [comment]
v2.1.0 contains your changes. It's available now on jcenter. It can take a day or so to propagate to MavenCentral

To get it from jCenter now you can add the following to `build.gradle` (assuming your using gradle)
```
repositories {
    maven {
        url  "https://dl.bintray.com/cdimascio/maven" 
    }
}
     
```

**Comment by cdimascio** [comment]
@all-contributors add @reinterpretcat for code

**Pull request merged**
