### PR TITLE
Fix issue of returns success for empty body

### PR DESCRIPTION
**Pull request by marcinziolo**

### CODE REVIEW

**Comment by cdimascio** [comment]
Thanks for the PR. 
Question for you, when you define the OpenAPI specification for your route, did you set the request body as **required: true**
e.g.

```
 /pets:
    post:
      summary: Add a new pet
      requestBody:
        description: Optional description in *Markdown*
        required: true .  # <------ do you have this set?
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
```

**Comment by marcinziolo** [comment]
> Thanks for the PR.
> Question for you, when you define the OpenAPI specification for your route, did you set the request body as **required: true**

Yes I set the request body as required. 
I think problem is that if we send empty body, mono is empty and therefore swagger validation isn't invoked at all.

**Comment by cdimascio** [comment]
Thanks. merging. will roll a new jar and post to maven/jcenter shortly

**Comment by cdimascio** [comment]
v2.1.1 is now available. It may take a day or so to make it to maven central.
It is available now on jcenter.

for gradle
```
repositories {
    maven {
        url  "https://dl.bintray.com/cdimascio/maven" 
    }
}
```

**Comment by cdimascio** [comment]
Thanks again for the PR! :)

**Pull request merged**
